# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20161213_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='url_random',
            field=models.CharField(default='19awiASdfjk', max_length=200),
        ),
    ]
